export const VAULT_PLANS = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "forever",
    desc: "For solo developers managing basic personal credentials.",
    popular: false,
    cta: "Start Free",
    features: [
      "Up to 2 Clients",
      "Unlimited Projects & Secrets",
      "Delivery Timeline & Safety Buffer",
      "Standard Docked Sticky Notes",
      "AES-256 Zero-Knowledge Encryption",
      "Basic .env Import / Export",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: "$8",
    period: "/ mo",
    desc: "For freelancers & solo power users needing complete client handover & secret protection.",
    popular: true,
    cta: "Get Started with Pro",
    features: [
      "Unlimited Clients & Projects",
      "🛡️ Brute-Force Rate Limiting & Security Health Meter",
      "📦 1-Click Client Handover Package Generator",
      "🔀 Multi-Environment Keys (Dev / Staging / Prod)",
      "📌 Project Runbook Scratchpad & Milestone Notes",
      "⚡ API Renewal Watchdog & Advance Alerts",
      "🛡️ Delivery Safety Buffer Tracker",
      "💰 Monthly Client Spend & Savings Tracker",
      "Full Decrypted & Multi-Env .env Exports",
    ],
  },
  {
    id: "team",
    name: "Team",
    price: "$19",
    period: "/ mo",

    desc: "For agencies and teams collaborating securely on client infrastructure.",
    popular: false,
    cta: "Start with Team",
    features: [
      "Everything in Pro (Watchdog & Security Health)",
      "Shared Team Vaults (Owner covers all members)",
      "Role Permissions (Full Access vs Skeleton Only)",
      "Environment Role Scoping (Dev / Staging / Prod)",
      "Team Deliverables Checklist & Milestone Sync",
      "Skeleton .env.example for safe developer onboarding",
      "Centralized Team Key Revocation",
    ],
  },
];
