export const COLORS = {
  bg: "var(--bg-main, #06080D)",
  panel: "var(--panel-main, #0B0E17)",
  panelAlt: "var(--panel-alt, #101522)",
  cardBg: "var(--panel-card, #0F1420)",
  line: "var(--line-main, rgba(255, 255, 255, 0.08))",
  border: "var(--line-main, rgba(255, 255, 255, 0.08))",
  lineHover: "var(--line-hover, rgba(0, 210, 255, 0.4))",
  text: "var(--text-main, #F8FAFC)",
  textDim: "var(--text-dim, #94A3B8)",
  textFaint: "var(--text-faint, #64748B)",
  brass: "var(--brand-cyan, #00D2FF)",
  brassDim: "var(--brand-indigo, #6366F1)",
  brassBorder: "rgba(0, 210, 255, 0.35)",
  cyan: "var(--brand-cyan, #00D2FF)",
  indigo: "var(--brand-indigo, #6366F1)",
  violet: "var(--brand-violet, #8B5CF6)",
  green: "var(--green-main, #10B981)",
  red: "var(--red-main, #F43F5E)",
};

export const S = {
  centerScreen: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: COLORS.bg,
    fontFamily: "Inter, -apple-system, sans-serif",
    padding: 16,
    overflowY: "auto",
    WebkitOverflowScrolling: "touch",
    boxSizing: "border-box",
  },
  authCard: {
    boxSizing: "border-box",
    width: "100%",
    maxWidth: 400,
    background: "rgba(11, 14, 23, 0.92)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: 18,
    padding: "32px 28px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    boxShadow: "0 24px 50px -15px rgba(0, 0, 0, 0.85), 0 0 1px 1px rgba(255, 255, 255, 0.06)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
  },
  authHeader: { display: "flex", alignItems: "center", gap: 14, marginBottom: 4 },
  dialRing: {
    width: 44,
    height: 44,
    borderRadius: 12,
    border: "1px solid rgba(0, 210, 255, 0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    background: "linear-gradient(135deg, rgba(0, 210, 255, 0.15) 0%, rgba(99, 102, 241, 0.12) 100%)",
    boxShadow: "0 0 16px rgba(0, 210, 255, 0.2)",
  },
  eyebrow: { fontFamily: "JetBrains Mono, IBM Plex Mono, monospace", fontSize: 10.5, letterSpacing: "0.14em", color: COLORS.cyan, textTransform: "uppercase", marginBottom: 2 },
  authTitle: { fontFamily: "Outfit, Space Grotesk, sans-serif", fontSize: 19, fontWeight: 700, color: COLORS.text, margin: 0, letterSpacing: "-0.01em" },
  authSub: { fontSize: 13, color: COLORS.textDim, lineHeight: 1.5, margin: "0 0 6px" },
  label: { fontSize: 11, color: COLORS.textFaint, fontFamily: "JetBrains Mono, monospace", marginTop: 4, letterSpacing: "0.04em", textTransform: "uppercase" },
  input: {
    boxSizing: "border-box",
    background: COLORS.panelAlt,
    border: `1px solid ${COLORS.line}`,
    borderRadius: 10,
    padding: "11px 14px",
    color: COLORS.text,
    fontSize: 13.5,
    fontFamily: "Inter, sans-serif",
    width: "100%",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
  },
  errBox: {
    boxSizing: "border-box",
    display: "flex", alignItems: "center", gap: 8, color: COLORS.red, fontSize: 12.5,
    background: "rgba(244, 63, 94, 0.1)", border: "1px solid rgba(244, 63, 94, 0.3)", borderRadius: 10, padding: "10px 12px",
    width: "100%",
  },
  infoBox: {
    boxSizing: "border-box",
    display: "flex", alignItems: "center", gap: 8, color: COLORS.green, fontSize: 12.5,
    background: "rgba(16, 185, 129, 0.1)", border: "1px solid rgba(16, 185, 129, 0.3)", borderRadius: 10, padding: "10px 12px",
    width: "100%",
  },
  primaryBtn: {
    boxSizing: "border-box",
    width: "100%",
    marginTop: 6,
    background: "var(--aegis-gradient, linear-gradient(135deg, #00D2FF 0%, #3B82F6 50%, #6366F1 100%))",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 10,
    padding: "11px 16px",
    fontSize: 13.5,
    fontWeight: 600,
    fontFamily: "Inter, sans-serif",
    cursor: "pointer",
    boxShadow: "var(--aegis-btn-glow, 0 4px 20px -2px rgba(0, 210, 255, 0.35))",
    transition: "transform 0.18s ease, box-shadow 0.18s ease, filter 0.18s ease",
  },
  primaryBtnSm: {
    background: "var(--aegis-gradient, linear-gradient(135deg, #00D2FF 0%, #3B82F6 50%, #6366F1 100%))",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 12.5,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 6,
    cursor: "pointer",
    boxShadow: "0 2px 14px rgba(0, 210, 255, 0.3)",
    transition: "all 0.18s ease",
  },
  secondaryBtn: {
    background: "rgba(255, 255, 255, 0.04)",
    color: COLORS.text,
    border: `1px solid ${COLORS.line}`,
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 12.5,
    fontWeight: 500,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    transition: "all 0.18s ease",
  },
  dangerBtn: {
    background: "rgba(244, 63, 94, 0.08)",
    color: COLORS.red,
    border: "1px solid rgba(244, 63, 94, 0.3)",
    borderRadius: 8,
    padding: "8px 12px",
    fontSize: 12.5,
    display: "flex",
    alignItems: "center",
    gap: 6,
    cursor: "pointer",
    transition: "all 0.18s ease",
  },
  oauthBtn: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 10,
    background: "rgba(255, 255, 255, 0.03)", color: COLORS.text, border: `1px solid ${COLORS.line}`, borderRadius: 10,
    padding: "11px 16px", fontSize: 13.5, fontWeight: 500, fontFamily: "Inter, sans-serif", cursor: "pointer",
    transition: "all 0.18s ease",
  },
  securityGuaranteeBadge: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    background: "rgba(0, 210, 255, 0.07)",
    border: "1px solid rgba(0, 210, 255, 0.2)",
    borderRadius: 10,
    padding: "11px 14px",
    fontSize: 12,
    color: COLORS.textDim,
    lineHeight: 1.5,
    marginTop: 6,
  },
  formSecurityNotice: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 11.5,
    color: COLORS.green,
    background: "rgba(16, 185, 129, 0.09)",
    border: "1px solid rgba(16, 185, 129, 0.25)",
    borderRadius: 8,
    padding: "7px 12px",
  },
  dividerRow: { display: "flex", alignItems: "center", margin: "8px 0", gap: 12 },
  dividerLine: { flex: 1, height: 1, background: COLORS.line },
  dividerText: { fontSize: 11, color: COLORS.textFaint, fontFamily: "JetBrains Mono, monospace" },
  authLinks: { display: "flex", justifyContent: "space-between", marginTop: 8 },
  linkText: { fontSize: 12, color: COLORS.cyan, cursor: "pointer", fontWeight: 500 },

  app: { display: "flex", minHeight: "100vh", background: COLORS.bg, fontFamily: "Inter, sans-serif", color: COLORS.text, width: "100%" },
  sidebar: {
    width: 270,
    borderRight: `1px solid ${COLORS.line}`,
    background: "var(--sidebar-bg, #07090F)",
    display: "flex",
    flexDirection: "column",
    padding: "18px 14px",
    gap: 14,
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
  },
  sidebarHead: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "2px 6px 8px" },
  brandRow: { display: "flex", alignItems: "center", gap: 10 },
  brandText: { fontFamily: "Outfit, sans-serif", fontWeight: 800, fontSize: 16, letterSpacing: "-0.01em", color: COLORS.text },
  addClientBtn: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
    background: "linear-gradient(135deg, rgba(0, 210, 255, 0.08) 0%, rgba(99, 102, 241, 0.06) 100%)",
    border: "1px dashed rgba(0, 210, 255, 0.35)", color: COLORS.cyan, borderRadius: 10, padding: "9px 12px", fontSize: 12.5, fontWeight: 600, cursor: "pointer",
    transition: "all 0.18s ease",
  },
  tree: { flex: 1, overflowY: "auto", display: "flex", flexDirection: "column", gap: 3, marginTop: 4 },
  emptyTree: { fontSize: 12, color: COLORS.textFaint, padding: "10px 8px", lineHeight: 1.5 },
  treeClientRow: { display: "flex", alignItems: "center", gap: 8, padding: "9px 10px", borderRadius: 9, cursor: "pointer", fontSize: 13.5, transition: "background 0.15s ease" },
  treeProjectRow: { display: "flex", alignItems: "center", gap: 8, padding: "8px 10px 8px 28px", borderRadius: 8, cursor: "pointer", fontSize: 13, transition: "background 0.15s ease" },
  treeRowActive: {
    background: "linear-gradient(90deg, rgba(0, 210, 255, 0.14) 0%, rgba(99, 102, 241, 0.08) 100%)",
    borderLeft: `3px solid ${COLORS.cyan}`,
    color: "#FFFFFF",
  },
  treeLabel: { flex: 1, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", color: COLORS.text, fontSize: 13.5, fontWeight: 500 },
  treeCount: { fontFamily: "JetBrains Mono, monospace", fontSize: 11, color: COLORS.textFaint },
  addProjectRow: { display: "flex", alignItems: "center", gap: 7, padding: "8px 10px 8px 28px", fontSize: 12, color: COLORS.textFaint, cursor: "pointer", transition: "color 0.15s ease" },

  main: { flex: 1, padding: "24px 28px", overflowY: "auto", background: "transparent" },
  mainHeadRow: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 20, gap: 14, flexWrap: "wrap" },
  mainTitle: { fontFamily: "Outfit, sans-serif", fontSize: 24, fontWeight: 700, margin: 0, color: COLORS.text, letterSpacing: "-0.02em" },
  headActions: { display: "flex", gap: 10, alignItems: "center" },
  emptyState: { fontSize: 13, color: COLORS.textFaint, padding: "24px 0" },
  welcomeState: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "70vh", gap: 12, textAlign: "center" },
  welcomeTitle: { fontFamily: "Outfit, sans-serif", fontSize: 18, fontWeight: 600, color: COLORS.text },
  welcomeSub: { fontSize: 13, color: COLORS.textDim, maxWidth: 320, lineHeight: 1.6 },

  projectGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))", gap: 12 },
  projectTile: {
    background: "var(--panel-card, #0F1420)",
    border: `1px solid ${COLORS.line}`,
    borderRadius: 14,
    padding: "18px 16px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    boxShadow: "0 4px 18px rgba(0, 0, 0, 0.4)",
    transition: "all 0.2s ease",
  },
  projectTileAdd: {
    background: "transparent",
    border: `1px dashed rgba(255, 255, 255, 0.15)`,
    borderRadius: 14,
    padding: "18px 16px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    color: COLORS.textFaint,
    fontSize: 13,
    transition: "all 0.2s ease",
  },
  projectTileName: { fontFamily: "Outfit, sans-serif", fontSize: 14, fontWeight: 600, color: COLORS.text },
  projectTileMeta: { fontSize: 11, color: COLORS.textFaint, fontFamily: "JetBrains Mono, monospace" },

  textarea: {
    boxSizing: "border-box",
    background: COLORS.panelAlt,
    border: `1px solid ${COLORS.line}`,
    borderRadius: 10,
    padding: "12px 14px",
    color: COLORS.text,
    fontSize: 13,
    fontFamily: "JetBrains Mono, monospace",
    width: "100%",
    minHeight: 140,
    resize: "vertical",
    lineHeight: 1.6,
  },
  codeBox: {
    boxSizing: "border-box",
    background: "#07090F",
    border: `1px solid ${COLORS.line}`,
    borderRadius: 10,
    padding: "14px 16px",
    fontFamily: "JetBrains Mono, monospace",
    fontSize: 12.5,
    color: "#E2E8F0",
    maxHeight: 220,
    overflowY: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    lineHeight: 1.6,
  },
  planBadgeFounder: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, padding: "3px 9px", borderRadius: 8,
    background: "linear-gradient(135deg, rgba(0, 210, 255, 0.2) 0%, rgba(99, 102, 241, 0.25) 100%)",
    color: COLORS.cyan, border: `1px solid rgba(0, 210, 255, 0.5)`, textTransform: "uppercase", fontWeight: 700,
    boxShadow: "0 0 12px rgba(0, 210, 255, 0.2)",
  },
  rolePillOwner: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, padding: "3px 9px", borderRadius: 12,
    background: "rgba(0, 210, 255, 0.12)", color: COLORS.cyan, border: `1px solid rgba(0, 210, 255, 0.35)`,
  },
  rolePillMember: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, padding: "3px 9px", borderRadius: 12,
    background: "rgba(16, 185, 129, 0.12)", color: COLORS.green, border: `1px solid rgba(16, 185, 129, 0.35)`,
  },
  rolePillRestricted: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, padding: "3px 9px", borderRadius: 12,
    background: "rgba(244, 63, 94, 0.12)", color: COLORS.red, border: `1px solid rgba(244, 63, 94, 0.35)`,
  },
  pendingBadge: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, padding: "3px 9px", borderRadius: 12,
    background: "rgba(245, 158, 11, 0.12)", color: "#FBBF24", border: "1px solid rgba(245, 158, 11, 0.35)",
    display: "inline-flex", alignItems: "center", gap: 4,
  },
  activeBadge: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, padding: "3px 9px", borderRadius: 12,
    background: "rgba(16, 185, 129, 0.12)", color: COLORS.green, border: "1px solid rgba(16, 185, 129, 0.35)",
    display: "inline-flex", alignItems: "center", gap: 4,
  },
  memberRow: {
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12,
    background: "var(--panel-card, #0F1420)", border: `1px solid ${COLORS.line}`, borderRadius: 10, padding: "12px 14px",
  },

  // Watchdog & Renewal Styles
  watchdogCounter: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 10, fontWeight: 700, padding: "1px 6px",
    borderRadius: 10, background: "#E07A6D", color: "#1A1611", marginLeft: "auto",
  },
  watchdogStatGrid: {
    display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 14, marginBottom: 12,
  },
  watchdogStatCard: {
    background: "var(--panel-card, #0F1420)", border: `1px solid ${COLORS.line}`, borderRadius: 14, padding: "18px 20px",
    display: "flex", flexDirection: "column", gap: 8,
    boxShadow: "0 6px 20px -4px rgba(0, 0, 0, 0.5)",
  },
  watchdogStatLabel: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 11, color: COLORS.textFaint, letterSpacing: "0.06em", textTransform: "uppercase",
  },
  watchdogStatValue: {
    fontFamily: "Outfit, sans-serif", fontSize: 26, fontWeight: 800, color: COLORS.text, letterSpacing: "-0.02em",
  },
  watchdogCard: {
    background: "var(--panel-card, #0F1420)", border: `1px solid ${COLORS.line}`, borderRadius: 12, padding: "14px 18px",
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, transition: "all 0.18s ease",
  },
  watchdogCardUrgent: {
    background: "rgba(244, 63, 94, 0.06)", border: "1px solid rgba(244, 63, 94, 0.35)",
  },
  urgencyPillCritical: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, letterSpacing: "0.03em", padding: "3px 9px",
    borderRadius: 6, background: "rgba(244, 63, 94, 0.15)", color: "#FDA4AF", border: "1px solid rgba(244, 63, 94, 0.4)",
    fontWeight: 600, display: "inline-flex", alignItems: "center", gap: 5,
  },
  urgencyPillWarning: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, letterSpacing: "0.03em", padding: "3px 9px",
    borderRadius: 6, background: "rgba(245, 158, 11, 0.15)", color: "#FBBF24", border: "1px solid rgba(245, 158, 11, 0.4)",
    fontWeight: 600, display: "inline-flex", alignItems: "center", gap: 5,
  },
  urgencyPillActive: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 10.5, letterSpacing: "0.03em", padding: "3px 9px",
    borderRadius: 6, background: "rgba(16, 185, 129, 0.12)", color: COLORS.green, border: "1px solid rgba(16, 185, 129, 0.35)",
    fontWeight: 500, display: "inline-flex", alignItems: "center", gap: 4,
  },
  portalBtn: {
    background: "rgba(176,141,87,0.12)", color: COLORS.brass, border: `1px solid ${COLORS.brassDim}`,
    borderRadius: 6, padding: "6px 10px", fontSize: 11.5, fontWeight: 500, display: "inline-flex", alignItems: "center",
    gap: 4, cursor: "pointer", textDecoration: "none",
  },
  clientSpendBadge: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 11, padding: "3px 8px", borderRadius: 6,
    background: "rgba(176,141,87,0.1)", color: COLORS.brass, border: `1px solid ${COLORS.brassDim}`,
    display: "inline-flex", alignItems: "center", gap: 5,
  },
  savingsStatCard: {
    background: "var(--panel-main, #FFFFFF)", border: `1px solid ${COLORS.line}`, borderRadius: 10,
    padding: "14px 16px", display: "flex", flexDirection: "column", gap: 6,
    boxShadow: "var(--card-shadow)",
  },
  savingsBadge: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 11, fontWeight: 700, padding: "2px 8px",
    borderRadius: 6, background: "rgba(45,106,66,0.12)", color: COLORS.green, border: `1px solid rgba(45,106,66,0.3)`,
    display: "inline-flex", alignItems: "center", gap: 4,
  },
  canceledBadge: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 10.5, letterSpacing: "0.03em", padding: "2px 8px",
    borderRadius: 6, background: "rgba(143,169,140,0.15)", color: COLORS.green, border: `1px solid rgba(143,169,140,0.3)`,
    fontWeight: 600, display: "inline-flex", alignItems: "center", gap: 4,
  },
  intentToggleBtn: {
    flex: 1, padding: "8px 10px", borderRadius: 6, fontSize: 11.5, fontWeight: 600, border: "none",
    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
    transition: "all 0.15s ease",
  },
  historyRow: {
    background: COLORS.panelAlt, border: `1px solid ${COLORS.line}`, borderRadius: 8, padding: "10px 14px",
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10,
  },

  // Project Tabs & Delivery Tracker
  projectSubActionsBar: {
    display: "flex", gap: 8, marginBottom: 12,
    overflowX: "auto", WebkitOverflowScrolling: "touch", scrollbarWidth: "none",
    flexWrap: "nowrap", alignItems: "center", paddingBottom: 2,
  },
  actionChipBtn: {
    background: "var(--panel-card, #0F1420)", border: `1px solid ${COLORS.line}`, borderRadius: 8,
    padding: "7px 14px", fontSize: 12, fontWeight: 500, color: COLORS.text,
    cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 6,
    whiteSpace: "nowrap", flexShrink: 0, transition: "all 0.18s ease",
    boxShadow: "0 2px 8px rgba(0,0,0,0.3)", outline: "none",
  },
  projectTabNav: {
    display: "flex", gap: 8, borderBottom: `1px solid ${COLORS.line}`, paddingBottom: 10, marginBottom: 16,
    overflowX: "auto", WebkitOverflowScrolling: "touch", scrollbarWidth: "none",
  },
  projectTabBtn: {
    background: COLORS.panelAlt, border: `1px solid ${COLORS.line}`, borderRadius: 8, padding: "8px 15px",
    fontSize: 12.5, fontWeight: 600, color: COLORS.textDim, cursor: "pointer", display: "flex", alignItems: "center",
    gap: 7, transition: "all 0.15s ease", outline: "none", userSelect: "none", flexShrink: 0,
  },
  projectTabBtnActive: {
    background: "linear-gradient(135deg, rgba(0, 210, 255, 0.15) 0%, rgba(99, 102, 241, 0.1) 100%)",
    borderColor: "rgba(0, 210, 255, 0.5)",
    color: "#00D2FF",
    boxShadow: "0 0 16px rgba(0, 210, 255, 0.2)",
  },
  deadlineGrid: {
    display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12, marginBottom: 14,
  },
  deadlineCard: {
    background: "var(--panel-card, #0F1420)", border: `1px solid ${COLORS.line}`, borderRadius: 12, padding: "14px 16px",
    display: "flex", flexDirection: "column", gap: 6, position: "relative",
    boxShadow: "var(--card-shadow)",
  },
  greyDaysCard: {
    background: "rgba(16, 185, 129, 0.08)", border: "1px solid rgba(16, 185, 129, 0.3)", borderRadius: 12,
    padding: "14px 16px", display: "flex", flexDirection: "column", gap: 6,
  },
  countdownTimerPill: {
    fontFamily: "JetBrains Mono, monospace", fontSize: 11, fontWeight: 700, padding: "3px 9px",
    borderRadius: 6, background: "rgba(244, 63, 94, 0.12)", color: COLORS.red, border: "1px solid rgba(244, 63, 94, 0.3)",
    display: "inline-flex", alignItems: "center", gap: 5,
  },
  scopeInfoBanner: {
    background: "rgba(0, 210, 255, 0.07)", border: `1px solid rgba(0, 210, 255, 0.2)`, borderRadius: 10,
    padding: "11px 16px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10,
    fontSize: 12.5, color: COLORS.textDim,
  },
  checklistItem: {
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, background: COLORS.panelAlt,
    border: `1px solid ${COLORS.line}`, borderRadius: 8, padding: "9px 12px", transition: "border-color 0.15s",
  },
  progressBarBg: {
    width: "100%", height: 6, background: COLORS.panelAlt, borderRadius: 4, overflow: "hidden", border: `1px solid ${COLORS.line}`,
  },
  progressBarFill: {
    height: "100%", background: "var(--aegis-gradient, linear-gradient(90deg, #00D2FF 0%, #10B981 100%))", borderRadius: 4, transition: "width 0.3s ease",
  },

  // Owner Command Center Dashboard
  ownerHeaderCard: {
    background: "var(--panel-card, #0F1420)",
    border: `1px solid ${COLORS.line}`, borderRadius: 14, padding: "20px 22px",
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 14, flexWrap: "wrap",
    boxShadow: "var(--card-shadow)",
  },
  quickStartCard: {
    background: "var(--panel-card, #0F1420)",
    border: `1px solid ${COLORS.line}`,
    borderRadius: 16,
    padding: "24px 26px",
    display: "flex",
    flexDirection: "column",
    gap: 18,
    boxShadow: "var(--card-shadow)",
  },
  overviewProjectCard: {
    background: "var(--panel-card, #0F1420)",
    border: `1px solid ${COLORS.line}`, borderRadius: 14, padding: "18px 20px",
    display: "flex", flexDirection: "column", gap: 12, cursor: "pointer",
    boxShadow: "var(--card-shadow)",
    transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  overviewOpenBtn: {
    display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
    background: "rgba(0, 210, 255, 0.08)", border: "1px solid rgba(0, 210, 255, 0.3)",
    color: COLORS.cyan, borderRadius: 8, padding: "8px 12px", fontSize: 12,
    fontWeight: 600, marginTop: 4, width: "100%", boxSizing: "border-box",
    transition: "all 0.18s ease",
  },
  breadcrumbBar: {
    display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "9px 14px", background: COLORS.panelAlt,
    border: `1px solid ${COLORS.line}`, borderRadius: 10, marginBottom: 16,
    fontSize: 12.5, color: COLORS.textDim, flexWrap: "wrap", gap: 8,
  },

  // Founder SuperAdmin HQ
  founderBanner: {
    background: "linear-gradient(135deg, rgba(0, 210, 255, 0.12) 0%, rgba(99, 102, 241, 0.08) 50%, rgba(15, 20, 32, 0.95) 100%)",
    border: "1px solid rgba(0, 210, 255, 0.35)", borderRadius: 16, padding: "22px 26px",
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, flexWrap: "wrap",
    boxShadow: "0 12px 30px -10px rgba(0, 0, 0, 0.7), 0 0 20px rgba(0, 210, 255, 0.1)",
  },
  founderRevenueCard: {
    background: COLORS.panel,
    border: `1px solid ${COLORS.line}`, borderRadius: 12, padding: "16px 18px",
    display: "flex", flexDirection: "column", gap: 6,
    boxShadow: "var(--card-shadow)",
  },
  userTableRow: {
    background: COLORS.panelAlt, border: `1px solid ${COLORS.line}`, borderRadius: 8, padding: "10px 14px",
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap",
  },

  // Environment Badges
  envBadgeDev: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 10, fontWeight: 700, padding: "2px 7px",
    borderRadius: 5, background: "rgba(100,160,240,0.15)", color: "#2B6CB0", border: "1px solid rgba(100,160,240,0.35)",
    textTransform: "uppercase", letterSpacing: "0.04em", display: "inline-flex", alignItems: "center", gap: 3,
  },
  envBadgeStaging: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 10, fontWeight: 700, padding: "2px 7px",
    borderRadius: 5, background: "rgba(235,165,60,0.15)", color: "#C0751A", border: "1px solid rgba(235,165,60,0.35)",
    textTransform: "uppercase", letterSpacing: "0.04em", display: "inline-flex", alignItems: "center", gap: 3,
  },
  envBadgeProd: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 10, fontWeight: 700, padding: "2px 7px",
    borderRadius: 5, background: "rgba(181,56,43,0.12)", color: COLORS.red, border: "1px solid rgba(181,56,43,0.35)",
    textTransform: "uppercase", letterSpacing: "0.04em", display: "inline-flex", alignItems: "center", gap: 3,
  },
  envBadgeGlobal: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 10, fontWeight: 700, padding: "2px 7px",
    borderRadius: 5, background: COLORS.panelAlt, color: COLORS.textDim, border: `1px solid ${COLORS.line}`,
    textTransform: "uppercase", letterSpacing: "0.04em", display: "inline-flex", alignItems: "center", gap: 3,
  },

  // Security Health Audit Score Card
  healthMeterCard: {
    background: COLORS.panel,
    border: `1px solid ${COLORS.line}`, borderRadius: 10, padding: "14px 16px",
    display: "flex", alignItems: "center", justifyContent: "space-between", gap: 14, flexWrap: "wrap",
    boxShadow: "var(--card-shadow)",
  },
  healthBadgeGood: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 11, fontWeight: 700, padding: "3px 9px",
    borderRadius: 6, background: "rgba(45,106,66,0.12)", color: COLORS.green, border: "1px solid rgba(45,106,66,0.3)",
    display: "inline-flex", alignItems: "center", gap: 4,
  },
  healthBadgeWarning: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 11, fontWeight: 700, padding: "3px 9px",
    borderRadius: 6, background: "rgba(235,165,60,0.15)", color: "#C0751A", border: "1px solid rgba(235,165,60,0.4)",
    display: "inline-flex", alignItems: "center", gap: 4,
  },

  // Command Palette
  cmdOverlay: {
    position: "fixed", inset: 0, background: "rgba(3, 4, 7, 0.85)", backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    display: "flex", alignItems: "flex-start", justifyContent: "center", paddingTop: "8vh",
    zIndex: 9999, overflowY: "auto", WebkitOverflowScrolling: "touch", padding: "16px 12px",
    boxSizing: "border-box",
  },
  cmdCard: {
    maxWidth: 600, width: "100%", background: "rgba(11, 14, 23, 0.96)",
    border: "1px solid rgba(0, 210, 255, 0.35)",
    borderRadius: 16,
    boxShadow: "0 28px 70px -15px rgba(0, 0, 0, 0.95), 0 0 24px rgba(0, 210, 255, 0.15)",
    overflow: "hidden", display: "flex",
    flexDirection: "column", boxSizing: "border-box",
  },
  cmdInputRow: {
    display: "flex", alignItems: "center", gap: 12, padding: "16px 20px", borderBottom: `1px solid ${COLORS.line}`,
    background: "rgba(16, 21, 34, 0.9)",
  },
  cmdInput: {
    flex: 1, background: "transparent", border: "none", color: COLORS.text, fontSize: 15, outline: "none",
    fontFamily: "Inter, sans-serif",
  },
  cmdList: {
    maxHeight: "55vh", overflowY: "auto", WebkitOverflowScrolling: "touch", padding: "10px", display: "flex", flexDirection: "column", gap: 3,
  },
  cmdItem: {
    display: "flex", alignItems: "center", justifyContent: "space-between", padding: "11px 16px",
    borderRadius: 10, cursor: "pointer", fontSize: 13.5, color: COLORS.text, transition: "all 0.12s ease",
  },
  cmdItemActive: {
    background: "linear-gradient(90deg, rgba(0, 210, 255, 0.15) 0%, rgba(99, 102, 241, 0.08) 100%)",
    color: COLORS.cyan,
  },
  
  // Instant Copy Fast Badge
  instantCopyBtn: {
    background: "rgba(0, 210, 255, 0.1)", border: "1px solid rgba(0, 210, 255, 0.3)", color: COLORS.cyan,
    borderRadius: 6, padding: "3px 9px", fontSize: 11, fontFamily: "JetBrains Mono, monospace",
    cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 5, transition: "all 0.15s ease",
  },

  // ──── Workspace (Store Room) Styles ────
  workspaceTopBar: {
    display: "flex", alignItems: "center", gap: 12, marginBottom: 16, flexWrap: "wrap",
  },
  workspaceSearchInput: {
    boxSizing: "border-box", background: COLORS.panelAlt, border: `1px solid ${COLORS.line}`,
    borderRadius: 10, padding: "9px 14px 9px 36px", color: COLORS.text, fontSize: 13,
    fontFamily: "Inter, sans-serif", flex: "1 1 220px", minWidth: 180, outline: "none",
  },
  workspaceGrid: {
    display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 14,
  },
  workspaceCard: {
    background: COLORS.panel, border: `1px solid ${COLORS.line}`, borderRadius: 12,
    overflow: "hidden", cursor: "pointer", display: "flex", flexDirection: "column",
    boxShadow: "var(--card-shadow)",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },
  workspaceCardHover: {
    borderColor: COLORS.brassDim, boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
  },
  workspaceCardThumb: {
    width: "100%", height: 140, objectFit: "cover", display: "block", background: COLORS.panelAlt,
  },
  workspaceCardIconArea: {
    width: "100%", height: 140, display: "flex", alignItems: "center", justifyContent: "center",
    background: COLORS.panelAlt,
  },
  workspaceCardTextPreview: {
    width: "100%", height: 140, padding: "12px 14px", background: COLORS.panelAlt,
    fontSize: 11.5, fontFamily: "IBM Plex Mono, monospace", color: COLORS.textDim,
    lineHeight: 1.5, overflow: "hidden", whiteSpace: "pre-wrap", wordBreak: "break-word",
  },
  workspaceCardBody: {
    padding: "12px 14px", display: "flex", flexDirection: "column", gap: 6, flex: 1,
  },
  workspaceCardTitle: {
    fontFamily: "Space Grotesk, sans-serif", fontSize: 13.5, fontWeight: 600, color: COLORS.text,
    whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis",
  },
  workspaceCardMeta: {
    display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap",
  },
  workspaceTypeBadge: {
    fontFamily: "IBM Plex Mono, monospace", fontSize: 9.5, letterSpacing: "0.04em", padding: "2px 7px",
    borderRadius: 5, textTransform: "uppercase", fontWeight: 500,
  },
  workspaceTagChip: {
    fontSize: 10, padding: "1px 6px", borderRadius: 4, background: COLORS.panelAlt,
    color: COLORS.textDim, border: `1px solid ${COLORS.line}`, fontFamily: "IBM Plex Mono, monospace",
  },
  workspaceSizeBadge: {
    fontSize: 10, color: COLORS.textFaint, fontFamily: "IBM Plex Mono, monospace",
  },
  workspaceCardActions: {
    display: "flex", gap: 2, padding: "0 14px 12px", flexWrap: "wrap",
  },

  // Storage Meter
  storageMeter: {
    display: "flex", alignItems: "center", gap: 10, padding: "6px 14px",
    background: COLORS.panelAlt, border: `1px solid ${COLORS.line}`, borderRadius: 8,
    flex: "0 0 auto",
  },
  storageMeterBarBg: {
    width: 100, height: 6, borderRadius: 3, background: "rgba(0,0,0,0.08)", overflow: "hidden",
  },
  storageMeterBarFill: {
    height: "100%", borderRadius: 3, transition: "width 0.3s ease, background 0.3s ease",
  },
  storageMeterText: {
    fontSize: 11, fontFamily: "IBM Plex Mono, monospace", color: COLORS.textDim, whiteSpace: "nowrap",
  },

  // Drop Zone
  dropZone: {
    boxSizing: "border-box", width: "100%", minHeight: 160, display: "flex", flexDirection: "column",
    alignItems: "center", justifyContent: "center", gap: 8,
    border: `2px dashed ${COLORS.line}`, borderRadius: 12, background: "rgba(0,0,0,0.02)",
    color: COLORS.textFaint, fontSize: 13, cursor: "pointer", transition: "all 0.15s ease",
    padding: 20,
  },
  dropZoneActive: {
    borderColor: COLORS.brass, background: "var(--highlight-bg, rgba(148,110,55,0.08))", color: COLORS.brass,
  },

  // Filter chips row
  workspaceFilterRow: {
    display: "flex", alignItems: "center", gap: 6, marginBottom: 16,
    overflowX: "auto", WebkitOverflowScrolling: "touch", flexWrap: "nowrap",
    paddingBottom: 4, scrollbarWidth: "none",
  },
  workspaceFilterChip: {
    fontSize: 12, padding: "5px 12px", borderRadius: 7, border: `1px solid ${COLORS.line}`,
    background: "transparent", color: COLORS.textDim, cursor: "pointer",
    fontFamily: "Inter, sans-serif", transition: "all 0.12s ease",
    flexShrink: 0, whiteSpace: "nowrap",
  },
  workspaceFilterChipActive: {
    borderColor: COLORS.brassDim, background: "var(--highlight-bg, rgba(148,110,55,0.12))", color: COLORS.brass,
  },
};

